version: "3.9"

services:
  fraud-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      poetry run uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
