# Use a minimal base image with Python 3.11
FROM python:3.11-slim

# Install required system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the base requirements
COPY requirements-base.txt .

# Install Python dependencies and remove any cached files
RUN pip install --no-cache-dir -r requirements-base.txt


# Remove build tools if they are no longer needed
RUN apt-get purge -y build-essential && apt-get autoremove -y